# Set messages to "" to disable them
connectingMessage: "Connecting to %s server..."
connectingNoPermission: "You do not have permission to connect to %s server."
alreadyConnectedMessage: "You're already connected to %s server."
# Aliases
aliases:
## Example
#    server: 
#        "/somealias":
#            forward: false
#        "/somealias2":
#            forward: true
#            permission: any.bungee.permission
    Hub:
        "/hub":
            forward: false		
    PSMP:
        "/smp":
            forward: false		
        "/PSMP":
            forward: false
    Minigames:
        "/Minigames":

    Factions:
        "/factions":
            forward: false    
    Pixelmon:
        "/Pixelmon":
            forward: false
    Survival:
        "/survival":
            forward: false
    Temp-test-server:
        '/test':
            forward: false
    Bowplinko:
        '/bowplinko':
            forward: false
    Murder:
        '/murder':
            forward: false
    BlastOff:
        '/blast':
            forward: false
        '/blastoff':
            forward: false
    PS:
        '/ps':
            forward: false
    Festive:
        '/christmas':
            forward: false
    Troll:
        '/troll':
            forward: false
    Troll:
        '/t':
            forward: false