motds:
  generic:
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'
  dynamic:
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'
  - '&c                 Servers under maintenence.%newline                     discord.me/Trafourmium'