motds:
  generic:
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'
  dynamic:
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'
  - 'PMCcfba7e058b7bd9a7dd3b60b1f4f91ae0'